package com.insram.worknest.mapper.task.comment;

import com.insram.worknest.dto.task.comment.CommentCreateDto;
import com.insram.worknest.dto.task.comment.CommentResponseDto;
import com.insram.worknest.model.entities.task.Task;
import com.insram.worknest.model.entities.task.comment.Comment;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface CommentMapper {

    @Mapping(target = "task", source = "task")
    @Mapping(target = "id", ignore = true)          // auto-generated by DB
    @Mapping(target = "createdAt", ignore = true)

        // handled by entity default
    Comment toEntity(CommentCreateDto dto, Task task);

    @Mapping(source = "task.id", target = "taskId")
    CommentResponseDto toResponseDto(Comment comment);


}
